---
layout: cv
title: Alvin Guevara's Resume
---
# Alvin Guevara
Business Consultant, Realtor, Accountant.

<div id="webaddress">
<a href="alvin.g1524@gmail.com">alvin.g1524@gmail.com</a>
| <a href="https://www.linkedin.com/in/alvin-guevara/">My LinkedIn Profile</a>
</div>

## Currently

Working as a Business Consultant at Highland Hay International, LLC

### Specialized in

Data Entry and Analytics, Sales, Marketing, and Customer Service

### Research interests

Real estate sales data analysis, export and revenue data tracking, economic nexus studies

## Education

`Expected Graduation December 2023`
__Brigham Young University Idaho, Rexburg, Idaho__

- BS in Business Analytics

`Graduated July 2019`
__Ensign College, Salt Lake City, Utah__

- AS in Integrated Studies
- AAS in Accounting
- AAS in Sales
- Certificate in Global Supply Chain & Operations

### Other Education

`Certified July 2022`
__Stukent__

- Mimic Marketing Principles

`Certified December 2017`
__Intuit Education__

- QuickBooks Pro/Premier 2016

## Experience Highlights

### Data Entry and Analytics

- Gather and analyze real estate sales data in excel.
- Create a statistical analysis for real estate sales data in R Studio.
- Gather, track, and analyze export and revenue data in excel.
- Wages analysis.
- Manage export compliance documents.
- Economic Nexus Study.
- Manage 36 Company books between QuickBooks Desktop 2020 & QuickBooks Online.

### Sales, Marketing, & Customer Service

- Retail sales.
- Inbound call sales.
- Cross selling.
- Door to Door sales.
- Negotiate real estate transactions.
- International market research.
- Website & Social Media marketing.

## Employment History

`Mar 2023 – Present`
__Highland Hay International, LLC__, Hamer ID

- Business Consultant – Full Time

`Apr 2019 – Present`
__Keller Williams Realty, Inc.__, South Jordan UT

- Realtor - Contract

`Jan 2018 – Present`
__B&B Bookkeeping and Accounting Services__, Salt Lake City UT

- Bookkeeper - Contract

`Sep 2020 – Jul 2021`
__SunForce Energy__, Las Vegas NV & Orem UT

- Energy Advisor - Contract

## Skills

- Experience with QuickBooks Online
- Experience with QuickBooks Desktop 2020
- Experience with MS Office
- Experience with MS Power BI
- Some experience with Python
- Some experience with R Studio
- Some experience with Tableau
- Empathizes and creates a good environment for customers and workers.

## Involvement

### Church of Jesus Christ of Latter-Day Saints

`Jul 2013 – Jul 2015`
__Volunteer Missionary__, Salem OR

- Led and trained groups of missionaries.

`Oct 2015 – Apr 2016`
__La Region Hispana__, Utah Region

- Committee Leader
- Held and organized 7 events.

`Apr 2016 – Apr 2017`
__La Region Hispana__, Utah Region

- Executive Committee Member
- Managed communication to 108 units by directing a group of 16 people.

## Honors & Awards

`Jan 2017`
__LDS Business College__, Salt Lake City UT

- Placed on Fall 2016 Deans List and Honor Roll.

## Languages

- ENGLISH - FLUENT
- SPANISH - FLUENT

*Further work experience and references available upon request.


<!-- ### Footer

Last updated: May 2013 -->